# Site
name: 'SingleSpark'
description: 'labour news from china'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'singlespark'
email: 'xinghuospark@protonmail.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
authors:
    Spark:
      name:           Spark
      avatar:         /assets/images/avatar1.jpg
      bio:            "Click FOLLOW to join me on Twitter!"
      email:          xinghuospark@protonmail.com
      twitter:        https://twitter.com/xinghuospark

 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
